### ISSUE TITLE
Create Assignment Two

### ISSUE THREAD

**Issue by rawrgulmuffins** [bike-barn/red-green-refactor#12]
# TODO List
- [ ] EOF token lexes (in next_token)
- [ ] + token lexes (in next_token)
- [ ] - token lexes (in next_token)
- [ ] `-` tests are stubbed and students fill them out
- [ ] Single digit integer token lexes
- [ ] Add simple Instructions for how to complete the assignment.
# NOTE

For this assignment I think we want to leave the subtraction tests mostly intact but have the students fill out the `test_input`, `expected_result`. They'll be able to use the `+` tests as a template and it lets us introduce them modifying tests.

**Comment by rawrgulmuffins** [comment]
#Closed with #17.
