### ISSUE TITLE
Create Assignment One

### ISSUE THREAD

**Issue by rawrgulmuffins** [bike-barn/red-green-refactor#9]
# TODO List
- [ ] Stub out token class.
- [ ] Stub out Interpreter (except for error handling). This isn't going to be used in the first assignment but it's simpler to include it from the start.
- [ ] Add REPL loop.
- [ ] Add token tests.
- [ ] Add (to start with) simple instructions for how to get tests to pass. 
# NOTES

Don't stub out error handling. This is something we don't expect students to know about and it's nice to have errors which make sense that don't crash the calculator.

**Comment by rawrgulmuffins** [comment]
This was closed when we pulled Tuckers stubbed out version of the Token class and it's tests into master.
